/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;

import Excepciones.clienteExistente;
import Excepciones.clienteNoExistente;
import Excepciones.lineaFacturaExistente;
import Excepciones.productoExistente;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfImage;
import com.itextpdf.text.pdf.PdfIndirectObject;
import com.itextpdf.text.pdf.PdfName;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cliente;
import modelo.Factura;
import modelo.LineaFactura;
import modelo.MetodoPago;
import modelo.Ordenador;
import modelo.Pieza;
import modelo.Producto;
import modelo.Servicio;
import modelo.Tienda;

/**
 *
 * @author mati
 */
public class GestionFicheros {

    public static File raiz;
    public static ArrayList<Tienda> listaTienda = new ArrayList<>();
    public static ArrayList<Factura> listaFacturas = new ArrayList<>();

    public static File getRaiz() {
        return raiz;
    }

    public static void setRaiz(File raiz) {
        GestionFicheros.raiz = raiz;
    }

    public static ArrayList<Tienda> getListaTienda() {
        return listaTienda;
    }

    public static void setListaTienda(ArrayList<Tienda> listaTienda) {
        GestionFicheros.listaTienda = listaTienda;
    }

    public static void generarDocumentoFactura(Factura f) throws FileNotFoundException, DocumentException, IOException {
        Document document = new Document();
        File fact = new File("tienda/facturas/PDF/" + f.getId() + ".pdf");
        if (!fact.exists()) {
            fact.createNewFile();
        }
        PdfWriter.getInstance(document, new FileOutputStream(fact));
        document.open();
        añadirMetadata(document);
        añadirTituloPagina(document, f);
        añadirContenido(document, f);
        document.close();
        añadirImagen(document, fact, new File("tienda/facturas/PDF/" + f.getId() + "ConIMG.pdf"
        ), new File("125.png")
        );
    }

    public static void añadirMetadata(Document doc) {
        doc.addTitle(listaTienda.get(0).getNombre());
        doc.addSubject(listaTienda.get(0).getDireccion());
        doc.addKeywords(listaTienda.get(0).getCIF());
        doc.addAuthor(listaTienda.get(0).getTelefono());
        doc.addAuthor(listaTienda.get(0).getWeb());
    }

    public static void añadirTituloPagina(Document document, Factura f)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        añadirLineasVacias(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Tienda dedicada a la venta de componentes" + listaTienda.get(0).getNombre()));
        preface.add(new Paragraph(listaTienda.get(0).getDireccion() + " " + listaTienda.get(0).getTelefono() + " "));
        preface.add(new Paragraph(listaTienda.get(0).getWeb() + " " + "Contamos con " + listaTienda.get(0).getListaClientes().size() + " clientes satisfechos"));
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Factura generada por: " + System.getProperty("user.name") + ", el dia " + new Date()));//$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$

        añadirLineasVacias(preface, 1);

        /*preface.add(new Paragraph(
                "This document is a preliminary version and not subject to your license agreement or any other agreement with vogella.com ;-)."));
         */
        document.add(preface);
        //document.newPage();
    }

    public static void añadirContenido(Document document, Factura f) throws DocumentException {
        Paragraph preface = new Paragraph();
        añadirLineasVacias(preface, 3);
        boolean primeraVez = true;
        //Crear tabla
        for (int i = 0; i < f.getListaLineas().size(); i++) {
            createTable(preface, primeraVez, f, i);
            primeraVez = false;
        }
        añadirLineasVacias(preface, 2);
        document.add(preface);

        Paragraph preface2 = new Paragraph();
        calcularResultadoYPDF(preface2, f);
        document.add(preface2);
    }

    public static void createTable(Paragraph subCatPart, boolean primeraVez, Factura f, int i) throws BadElementException {
        //PdfPTable table = new PdfPTable(3);
        PdfPTable table = new PdfPTable(new float[]{20, 85, 20, 20});
        table.setWidthPercentage(100);
        LineaFactura lf = f.getListaLineas().get(i);
        if (primeraVez == true) {
            PdfPCell c1 = new PdfPCell(new Phrase("Codigo linea"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);

            c1 = new PdfPCell(new Phrase("Producto"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);

            c1 = new PdfPCell(new Phrase("Cantidad"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);

            c1 = new PdfPCell(new Phrase("Coste"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);
            table.setHeaderRows(1);
        }
        String codLinea = "" + lf.getCodigoLinea();
        String cantidad = "" + lf.getCantidad();
        String coste = "" + lf.getCoste();
        table.addCell(codLinea);
        table.addCell(lf.getProducto().toString());
        table.addCell(cantidad);
        table.addCell(coste);

        subCatPart.add(table);

    }

    public static void añadirLineasVacias(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    public static void añadirImagen(Document document, File source, File dest, File img) {
        try {
            PdfReader reader = new PdfReader(source.getAbsolutePath());
            PdfStamper stamer = new PdfStamper(reader, new FileOutputStream(dest.getAbsolutePath()));
            Image image = Image.getInstance(img.getAbsolutePath());
            PdfImage stream = new PdfImage(image, "", null);
            stream.put(new PdfName("ITXT_SpecialId"), new PdfName("123456789"));
            PdfIndirectObject ref = stamer.getWriter().addToBody(stream);
            image.setDirectReference(ref.getIndirectReference());
            image.setAbsolutePosition(450, 700);
            PdfContentByte over = stamer.getOverContent(1);
            over.addImage(image);
            stamer.close();
            reader.close();
        } catch (IOException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void calcularResultadoYPDF(Paragraph subCatPart, Factura f) {
        double totalBruto = 0;
        double totalNeto = 0;
        double IVA = 1.21;
        double dtoVolumen = 0.98;
        double dtoCrypto = 0.90;
        double descuentos;
        double dtoProntoPago = 0.97;
        for (int i = 0; i < f.getListaLineas().size(); i++) {
            totalBruto += f.getListaLineas().get(i).getCoste();
        }
        if (f.getListaLineas().size() > 10) {
            if (f.getMp() == MetodoPago.BITCOIN || f.getMp() == MetodoPago.ETHEREUM || f.getMp() == MetodoPago.LITECOIN || f.getMp() == MetodoPago.IOTA) {
                totalNeto = (totalBruto * dtoProntoPago * dtoVolumen * dtoCrypto) * IVA;
                descuentos = (totalBruto * 0.02) + (totalBruto * 0.03) + (totalBruto * 0.10);
            } else {
                totalNeto = (totalBruto * dtoProntoPago * dtoVolumen) * IVA;
                descuentos = (totalBruto * 0.02) + (totalBruto * 0.03);
            }
        } else {
            if (f.getMp() == MetodoPago.BITCOIN || f.getMp() == MetodoPago.ETHEREUM || f.getMp() == MetodoPago.LITECOIN || f.getMp() == MetodoPago.IOTA) {
                totalNeto = (totalBruto * dtoProntoPago * dtoCrypto) * IVA;
                descuentos = (totalBruto * 0.03) + (totalBruto * 0.10);
            } else {
                totalNeto = (totalBruto * dtoProntoPago) * IVA;
                descuentos = (totalBruto * 0.03);
            }
        }

        PdfPTable table = new PdfPTable(new float[]{20, 20, 20, 20});
        table.setWidthPercentage(100);

        PdfPCell c1 = new PdfPCell(new Phrase("Importe bruto"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Descuentos"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("IVA"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Importe neto"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        String importeBruto = "" + totalBruto;
        String descuentoStr = "" + descuentos;
        String IVAstr = "" + (totalBruto * 0.21);
        String importeNeto = "" + totalNeto;
        table.addCell(importeBruto);
        table.addCell(descuentoStr);
        table.addCell(IVAstr);
        table.addCell(importeNeto);
        subCatPart.add(table);
    }

    public static void generacionDeEstructurasBasicas() throws IOException {
        File rutaInicial = new File("tienda");
        if (!rutaInicial.exists()) {
            rutaInicial.mkdir();
        }
        File rutaClientes = new File("tienda/clientes");
        if (!rutaClientes.exists()) {
            rutaClientes.mkdir();
        }
        File rutaEmpleados = new File("tienda/empleados");
        if (!rutaEmpleados.exists()) {
            rutaEmpleados.mkdir();
        }
        File rutaFacturas = new File("tienda/facturas");
        if (!rutaFacturas.exists()) {
            rutaFacturas.mkdir();
        }
        File rutaProductos = new File("tienda/productos");
        if (!rutaProductos.exists()) {
            rutaProductos.mkdir();
        }
        File rutaFacturasCSV = new File("tienda/facturas/CSV");
        if (!rutaFacturasCSV.exists()) {
            rutaFacturasCSV.mkdir();
        }
        File rutaFacturasPDF = new File("tienda/facturas/PDF");
        if (!rutaFacturasPDF.exists()) {
            rutaFacturasPDF.mkdir();
        }

    }

    public static void altaCliente(Cliente c) throws IOException {
        File rutaInicial = new File("tienda/clientes");
        if (rutaInicial.exists()) {
            File ficheroCliente = new File(rutaInicial.getAbsolutePath() + "/" + c.getDni() + ".csv");
            ficheroCliente.createNewFile();
            PrintWriter pw = new PrintWriter(ficheroCliente);
            pw.print(c.formatear());
            pw.close();
        } else {
            System.out.println("No fueron inicializadas las rutas basicas, pruebe otra vez");
            try {
                generacionDeEstructurasBasicas();
            } catch (IOException ex) {
                Logger.getLogger(GestionFicheros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public static void bajaCliente(Cliente c) {
        File rutaInicial = new File("tienda/clientes/" + c.getDni() + ".csv");
        if (rutaInicial.exists()) {
            System.out.println("eliminando ficheros...");
            rutaInicial.delete();
        } else {
            System.out.println("No fueron inicializadas las rutas basicas, pruebe otra vez");
            try {
                generacionDeEstructurasBasicas();
            } catch (IOException ex) {
                Logger.getLogger(GestionFicheros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public static void altaProducto(Producto p) throws IOException {
        File rutaInicial = new File("tienda/productos");
        if (rutaInicial.exists()) {
            File ficheroProducto = new File(rutaInicial.getAbsolutePath() + "/" + p.getCodigo() + ".csv");
            ficheroProducto.createNewFile();
            PrintWriter pw = new PrintWriter(ficheroProducto);
            pw.print(p.formatear());
            pw.close();
        } else {
            System.out.println("No fueron inicializadas las rutas basicas, pruebe otra vez");
            try {
                generacionDeEstructurasBasicas();
            } catch (IOException ex) {
                Logger.getLogger(GestionFicheros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public static void altaFactura(Factura f) throws IOException {
        File rutaInicial = new File("tienda/facturas/CSV");
        if (rutaInicial.exists()) {
            File ficheroFactura = new File(rutaInicial.getAbsolutePath() + "/" + f.getId() + ".csv");
            ficheroFactura.createNewFile();
            PrintWriter pw = new PrintWriter(ficheroFactura);
            pw.print(f.formatear());
            pw.close();
        } else {
            System.out.println("No fueron inicializadas las rutas basicas, pruebe otra vez");
            try {
                generacionDeEstructurasBasicas();
            } catch (IOException ex) {
                Logger.getLogger(GestionFicheros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public static void cargarFacturas() throws FileNotFoundException, ParseException, lineaFacturaExistente {
        File rutaInicial = new File("tienda/facturas/CSV");
        File[] facturas = rutaInicial.listFiles();
        System.out.println("Hay " + facturas.length + " facturas");
        for (int i = 0; i < facturas.length; i++) {
            Scanner sc = new Scanner(facturas[i]);
            Factura nuevaFactura = null;
            while (sc.hasNext()) {
                String linea = sc.nextLine();
                String[] datos = linea.split(";");
                String lineaFactura = "";
                Cliente c = controlador.GestionFicheros.listaTienda.get(0).buscarCliente(datos[1]);//De esta forma tenemos el cliente
                if (datos[4].equalsIgnoreCase("efectivo")) {
                    nuevaFactura = new Factura(Integer.parseInt(datos[0]), c, datos[2], Double.parseDouble(datos[3]), MetodoPago.EFECTIVO);
                }
                if (datos[4].equalsIgnoreCase("TARJETA_BANCARIA")) {
                    nuevaFactura = new Factura(Integer.parseInt(datos[0]), c, datos[2], Double.parseDouble(datos[3]), MetodoPago.TARJETA_BANCARIA);
                }
                if (datos[4].equalsIgnoreCase("BITCOIN")) {
                    nuevaFactura = new Factura(Integer.parseInt(datos[0]), c, datos[2], Double.parseDouble(datos[3]), MetodoPago.BITCOIN);
                }
                if (datos[4].equalsIgnoreCase("ETHEREUM")) {
                    nuevaFactura = new Factura(Integer.parseInt(datos[0]), c, datos[2], Double.parseDouble(datos[3]), MetodoPago.ETHEREUM);
                }
                if (datos[4].equalsIgnoreCase("LITECOIN")) {
                    nuevaFactura = new Factura(Integer.parseInt(datos[0]), c, datos[2], Double.parseDouble(datos[3]), MetodoPago.LITECOIN);
                }
                if (datos[4].equalsIgnoreCase("IOTA")) {
                    nuevaFactura = new Factura(Integer.parseInt(datos[0]), c, datos[2], Double.parseDouble(datos[3]), MetodoPago.IOTA);
                }
                int k = 0;
                for (int j = 6; j < datos.length; j++) {
                    lineaFactura += datos[j] + ";";
                    if (k == 4) {
                        k = 0;
                        //System.out.println(lineaFactura);
                        String[] lfarray = lineaFactura.split(";");
                        //System.out.println("busqueda de producto por " + lfarray[1]);
                        Producto p = controlador.GestionFicheros.listaTienda.get(0).buscarProducto(lfarray[1].trim());
                        LineaFactura lf = new LineaFactura(Integer.parseInt(lfarray[0]), p, Integer.parseInt(lfarray[2]), Double.parseDouble(lfarray[3]));
                        nuevaFactura.añadirLineaAFacturaExpress(lf);
                    }
                    k++;
                }

            }
            controlador.GestionFicheros.listaFacturas.add(nuevaFactura);
            sc.close();
        }
    }

    public static void redistribuirFacturas() {
        ArrayList<Cliente> listaClientes = controlador.GestionFicheros.listaTienda.get(0).getListaClientes();
        for (int i = 0; i < listaClientes.size(); i++) {
            for (int j = 0; j < listaFacturas.size(); j++) {
                if (listaClientes.get(i).getDni().equalsIgnoreCase(listaFacturas.get(j).getCliente().getDni())) {
                    listaClientes.get(i).getFacturas().add(listaFacturas.get(j));
                    System.out.println("Añadida factura a " + listaClientes.get(i).getNombre());
                }
            }
        }

    }

    public static void cargarProductos() throws FileNotFoundException, productoExistente {
        File rutaInicial = new File("tienda/productos/");
        File[] productos = rutaInicial.listFiles();
        System.out.println("Hay " + productos.length + " productos");
        for (int i = 0; i < productos.length; i++) {
            Scanner sc = new Scanner(productos[i]);
            while (sc.hasNext()) {
                String linea = sc.nextLine();
                String[] contenido = linea.split(";");
                if (contenido[0].equalsIgnoreCase("Pieza")) {
                    Pieza p = new Pieza(Integer.parseInt(contenido[4]), contenido[2], contenido[1], Double.parseDouble(contenido[3]));
                    controlador.GestionFicheros.listaTienda.get(0).añadirProducto(p);
                }
                if (contenido[0].equalsIgnoreCase("Ordenador")) {
                    Ordenador o = new Ordenador(Integer.parseInt(contenido[4]), contenido[2], contenido[1], Double.parseDouble(contenido[3]));
                    controlador.GestionFicheros.listaTienda.get(0).añadirProducto(o);
                }
                if (contenido[0].equalsIgnoreCase("Servicio")) {
                    Servicio s = new Servicio(Double.parseDouble(contenido[4]), contenido[2], contenido[1], Double.parseDouble(contenido[3]));
                    controlador.GestionFicheros.listaTienda.get(0).añadirProducto(s);
                }
            }
            sc.close();
        }

    }

    public static void cargarCliente() throws FileNotFoundException, IOException, clienteExistente {
        File rutaInicial = new File("tienda/clientes/");
        File[] clientes = rutaInicial.listFiles();
        System.out.println("Hay " + clientes.length + " clientes");
        for (int i = 0; i < clientes.length; i++) {
            Scanner sc = new Scanner(clientes[i]);
            String[] datos;
            Cliente c;
            while (sc.hasNext()) {
                String linea = sc.nextLine();
                datos = linea.split(";");
                c = new Cliente(datos[1], datos[2], datos[0], datos[3]);
                controlador.GestionFicheros.listaTienda.get(0).añadirCliente(c);
            }
            sc.close();
        }
    }

}
